# Example of how to add the coverage reporting to your workflow
# Copy and paste these steps into your existing workflow

# After your existing test step that runs pytest with coverage:
- name: Generate Coverage Reports
  run: |
    bash scripts/ci_post_test.sh

- name: Upload Coverage Reports
  uses: actions/upload-artifact@v3
  with:
    name: coverage-reports-${{ matrix.python-version }}
    path: |
      htmlcov/
      coverage.xml
      coverage-badge.svg
