[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "copick-torch"
version = "0.0.1"
description = "Copick Torch Integration"
dependencies = [
    "torch",
    "monai",
    "dask",
    "einops",
    "h5py",
    "numpy<2",
    "rich",
    "scikit-image",
    "scipy",
    "mrcfile",
    "copick",
    "numcodecs<0.16.0",
    "pandas>=2.2.3",
    "matplotlib>=3.10.1",
    "pyarrow>=19.0.1",
    "pytest>=8.3.5",
    "scikit-learn>=1.6.1",
    "torchvision>=0.21.0",
]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-cov"
]

[project.scripts]
coverage-report = "scripts.coverage_report:main"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.envs.default]
dependencies = ["pytest"]

[tool.pytest.ini_options]
testpaths = ["tests"]
