[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "copick-torch"
version = "0.0.1"
description = "Copick Torch Integration"
dependencies = [
    "torch",
    "monai",
    "dask",
    "einops",
    "h5py",
    "numpy<2",
    "rich",
    "scikit-image",
    "scipy",
    "mrcfile",
    "copick"
]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-cov"
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.envs.default]
dependencies = ["pytest"]

[tool.pytest.ini_options]
testpaths = ["tests"]
